name: app_giao_hang
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  dio: ^5.3.4
  intl: ^0.18.0
  connecteo: ^2.1.1
  json_annotation: ^4.8.1
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.2
  firebase_messaging: ^14.6.2
  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.2
  firebase_auth: ^4.10.0
  flutter_local_notifications: ^14.1.1
  get_storage: ^2.1.1
  flutter_svg: ^2.0.6
  shimmer: ^3.0.0
  photo_view: ^0.14.0
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.3
  pin_code_fields: ^7.4.0
  sprintf: ^7.0.0
  permission_handler: ^10.3.0
  event_bus: ^2.0.0
  dots_indicator: ^3.0.0
  http_parser: ^4.0.2
  path: ^1.8.3
  wakelock_plus: ^1.1.1
  logger: ^2.0.2
  url_launcher: ^6.1.14
  #app_tracking_transparency: ^2.0.4
  #flutter_widget_from_html: ^0.10.0
  path_drawing: ^1.0.1
  fluttertoast: ^8.2.2
  lottie: ^2.4.0
  #Gallery
  image_cropper: ^5.0.0
  #photo_manager: 2.7.2
  path_provider: ^2.0.15
  camera: ^0.10.5+2
  flutter_cupertino_datetime_picker: ^3.0.0
  syncfusion_flutter_charts: ^23.2.4
  #Wifi
  wifi_iot: ^0.3.18+1
  wifi_scan: ^0.4.0+2
  location: 5.0.3
  network_info_plus: ^4.0.2
  open_settings: ^2.0.2
  package_info_plus: ^4.1.0
  #Location
  geolocator: ^10.1.0
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_flavorizr: ^2.2.1

flutter_gen:
  output: lib/res/gen/ # Optional (default: lib/gen/)
  line_length: 180 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/json/